package com.maxtauro.monopolywallet.util.NotificationTypes


/**
 * TODO add authoring, date, and desc
 */

enum class StandardNotifications {

    START_GAME_NOTIFICATION,
    END_GAME_NOTIFICATION,
    LEAVE_GAME,
    PAY_BANK_INTENT_NOTIFICATION,
    PAY_BANK_CONFIRMATION_NOTIFICATION,
    REQUEST_PAYMENT_FROM_BANK,
    APPROVE_BANK_REQUEST,
    PAY_USER,
    REQUEST_PAYMENT_FROM_USER,
    RESPOND_TO_USER_PAYMENT,
    RESPOND_TO_USER_PAYMENT_REQUEST,

    GENERIC_NOTIFICATION

}